services:
  - type: web
    name: infusion-ia-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SERVICE_ROLE_KEY
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL_MARKETING
        sync: false
      - key: AI_MODEL_LOGO
        sync: false
      - key: AI_MODEL_PROMPT_OPT
        sync: false
      - key: AI_MODEL_VALIDATOR
        sync: false
      - key: LEONARDO_API_KEY
        sync: false
